package flywheel

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

func TestLearningsAssignsSequentialIDs(t *testing.T) {
	dir := t.TempDir()
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning",
		Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "runs/t1.r1.jsonl", Ask: "repeat",
		Signals: []string{"slow", "terse"}}); err != nil {
		t.Fatalf("AppendEvent() learning 1 error = %v", err)
	}
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:01Z", Task: "t1", Kind: "learning",
		Severity: "P2", Title: "Cache", Observed: "misses", Evidence: "runs", Ask: "warm"}); err != nil {
		t.Fatalf("AppendEvent() learning 2 error = %v", err)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	views := Learnings(events)
	if len(views) != 2 {
		t.Fatalf("Learnings() = %d views, want 2", len(views))
	}
	if views[0].ID != "L-01" || views[0].Severity != "P1" || views[0].Title != "Terse" {
		t.Errorf("Learnings()[0] = %+v, want L-01 P1 Terse", views[0])
	}
	if views[1].ID != "L-02" || views[1].Severity != "P2" || views[1].Title != "Cache" {
		t.Errorf("Learnings()[1] = %+v, want L-02 P2 Cache", views[1])
	}
	if got := NextLearningID(events); got != "L-03" {
		t.Errorf("NextLearningID() = %q, want L-03", got)
	}
}

func TestLearningsDismissMarksWithoutRenumbering(t *testing.T) {
	dir := t.TempDir()
	for i, e := range []Event{
		{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"},
		{TS: "2026-09-16T00:00:01Z", Task: "t1", Kind: "learning", Severity: "P2", Title: "Cache", Observed: "misses", Evidence: "e2", Ask: "a2"},
	} {
		if err := AppendEvent(dir, e); err != nil {
			t.Fatalf("AppendEvent() learning %d error = %v", i, err)
		}
	}
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:02Z", Task: "t1", Kind: "dismissed", ID: "L-01", Note: "fixed"}); err != nil {
		t.Fatalf("AppendEvent() dismissed error = %v", err)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	views := Learnings(events)
	if len(views) != 2 {
		t.Fatalf("Learnings() = %d views, want 2 (dismiss must not renumber)", len(views))
	}
	if !views[0].Dismissed || views[0].Reason != "fixed" {
		t.Errorf("Learnings()[0] = %+v, want dismissed with reason fixed", views[0])
	}
	if views[1].ID != "L-02" || views[1].Dismissed {
		t.Errorf("Learnings()[1] = %+v, want L-02 untouched", views[1])
	}
}

func TestLearningsDismissUnknownIDIsNoop(t *testing.T) {
	dir := t.TempDir()
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning",
		Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}); err != nil {
		t.Fatalf("AppendEvent() learning error = %v", err)
	}
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:01Z", Task: "t1", Kind: "dismissed", ID: "L-09", Note: "x"}); err != nil {
		t.Fatalf("AppendEvent() dismissed error = %v", err)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	views := Learnings(events)
	if len(views) != 1 || views[0].Dismissed {
		t.Errorf("Learnings() = %+v, want the sole learning untouched by an unknown dismiss target", views)
	}
}

func TestWriteLearningsFile(t *testing.T) {
	dir := t.TempDir()
	views := []LearningView{
		{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "runs/t1.r1.jsonl",
			Ask: "repeat", Signals: []string{"slow", "terse"}, Dismissed: true, Reason: "fixed"},
		{ID: "L-02", Severity: "P2", Title: "Cache", Observed: "misses", Evidence: "runs", Ask: "warm"},
	}
	if err := WriteLearningsFile(dir, views); err != nil {
		t.Fatalf("WriteLearningsFile() error = %v", err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".flywheel", "learnings.md"))
	if err != nil {
		t.Fatalf("read .flywheel/learnings.md: %v", err)
	}
	want := "# Learnings\n" +
		"<!-- generated by flywheel feedback; do not edit by hand -->\n" +
		"\n## L-01 — Terse\n" +
		"severity: P1\n" +
		"observed: slow\n" +
		"evidence: runs/t1.r1.jsonl\n" +
		"ask: repeat\n" +
		"signals: slow, terse\n" +
		"dismissed: fixed\n" +
		"\n## L-02 — Cache\n" +
		"severity: P2\n" +
		"observed: misses\n" +
		"evidence: runs\n" +
		"ask: warm\n"
	if string(got) != want {
		t.Errorf("learnings.md =\n%s\nwant\n%s", got, want)
	}
	if _, err := os.Stat(filepath.Join(dir, "learnings.md")); !os.IsNotExist(err) {
		t.Errorf("repo-root learnings.md exists; want only .flywheel/learnings.md")
	}
}

func TestWriteLearningsFileRemovesMarkedRootCopy(t *testing.T) {
	dir := t.TempDir()
	old := filepath.Join(dir, "learnings.md")
	if err := os.WriteFile(old, []byte("# Learnings\n"+learningsMarker+"\nstale generated copy"), 0o644); err != nil {
		t.Fatalf("write marked root copy: %v", err)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	if err := WriteLearningsFile(dir, views); err != nil {
		t.Fatalf("WriteLearningsFile() error = %v", err)
	}
	if _, err := os.Stat(old); !os.IsNotExist(err) {
		t.Errorf("marked root copy %s still exists after migration (stat err=%v)", old, err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".flywheel", "learnings.md"))
	if err != nil {
		t.Fatalf("read .flywheel/learnings.md: %v", err)
	}
	if !strings.Contains(string(got), "Terse") {
		t.Errorf(".flywheel/learnings.md lost the learning:\n%s", got)
	}
}

func TestWriteLearningsFileLeavesUnmarkedRootCopy(t *testing.T) {
	dir := t.TempDir()
	old := filepath.Join(dir, "learnings.md")
	original := []byte("my own training notes\n")
	if err := os.WriteFile(old, original, 0o644); err != nil {
		t.Fatalf("write unmarked root copy: %v", err)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	if err := WriteLearningsFile(dir, views); err != nil {
		t.Fatalf("WriteLearningsFile() error = %v", err)
	}
	got, err := os.ReadFile(old)
	if err != nil {
		t.Fatalf("read root copy: %v", err)
	}
	if string(got) != string(original) {
		t.Errorf("unmarked root copy changed to %q, want %q untouched", got, original)
	}
}

func TestWriteLearningsFileFailedWriteLeavesOldCopy(t *testing.T) {
	dir := t.TempDir()
	old := filepath.Join(dir, "learnings.md")
	oldContent := "old content"
	if err := os.WriteFile(old, []byte(oldContent), 0o644); err != nil {
		t.Fatalf("write old root copy: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".flywheel"), []byte("not a dir"), 0o644); err != nil {
		t.Fatalf("write .flywheel blocker: %v", err)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	if err := WriteLearningsFile(dir, views); err == nil {
		t.Fatal("WriteLearningsFile() succeeded, want a write failure")
	}
	b, err := os.ReadFile(old)
	if err != nil {
		t.Fatalf("read old root copy: %v", err)
	}
	if string(b) != oldContent {
		t.Errorf("old root copy changed to %q, want %q untouched", b, oldContent)
	}
}

func TestWriteLearningsFileRefusesHandMaintainedDotFile(t *testing.T) {
	dir := t.TempDir()
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	curated := []byte("# Learnings\n\n## Hand written, precious\ndo not lose me\n")
	if err := os.MkdirAll(filepath.Dir(dot), 0o755); err != nil {
		t.Fatalf("mkdir .flywheel: %v", err)
	}
	if err := os.WriteFile(dot, curated, 0o644); err != nil {
		t.Fatalf("write curated file: %v", err)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	err := WriteLearningsFile(dir, views)
	if err == nil {
		t.Fatal("WriteLearningsFile() succeeded, want a refusal")
	} else if !strings.Contains(err.Error(), ".flywheel") {
		t.Errorf("refusal %q does not name the .flywheel path", err)
	}
	got, rerr := os.ReadFile(dot)
	if rerr != nil {
		t.Fatalf("read curated file: %v", rerr)
	}
	if string(got) != string(curated) {
		t.Errorf("curated file changed to %q, want %q byte-for-byte", got, curated)
	}
}

func TestWriteLearningsFileRegeneratesMarkedDotFile(t *testing.T) {
	dir := t.TempDir()
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	if err := os.MkdirAll(filepath.Dir(dot), 0o755); err != nil {
		t.Fatalf("mkdir .flywheel: %v", err)
	}
	if err := os.WriteFile(dot, []byte("# Learnings\n"+learningsMarker+"\n\n## L-00 — stale\nseverity: P0\n"), 0o644); err != nil {
		t.Fatalf("write marked file: %v", err)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	if err := WriteLearningsFile(dir, views); err != nil {
		t.Fatalf("WriteLearningsFile() error = %v", err)
	}
	got, err := os.ReadFile(dot)
	if err != nil {
		t.Fatalf("read marked file: %v", err)
	}
	if !strings.Contains(string(got), learningsMarker) {
		t.Errorf("regenerated file lost the marker:\n%s", got)
	}
	if !strings.Contains(string(got), "Terse") || strings.Contains(string(got), "stale") {
		t.Errorf("regenerated file = \n%s\nwant the new learning only", got)
	}
}

func TestWriteLearningsFileLeavesReplacedRootFile(t *testing.T) {
	dir := t.TempDir()
	old := filepath.Join(dir, "learnings.md")
	marked := []byte("# Learnings\n" + learningsMarker + "\nstale generated copy\n")
	if err := os.WriteFile(old, marked, 0o644); err != nil {
		t.Fatalf("write marked root copy: %v", err)
	}
	replacement := filepath.Join(dir, "replacement.md")
	if err := os.WriteFile(replacement, []byte("hand-maintained notes\n"), 0o644); err != nil {
		t.Fatalf("write replacement: %v", err)
	}
	rfi, err := os.Stat(replacement)
	if err != nil {
		t.Fatalf("stat replacement: %v", err)
	}
	lstat := func(path string) (os.FileInfo, error) {
		if path == old {
			return rfi, nil
		}
		return os.Lstat(path)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	if err := writeLearningsFile(dir, views, lstat); err != nil {
		t.Fatalf("writeLearningsFile() error = %v", err)
	}
	got, err := os.ReadFile(old)
	if err != nil {
		t.Fatalf("read root copy: %v", err)
	}
	if string(got) != string(marked) {
		t.Errorf("replaced root copy was deleted or changed to %q, want %q left alone", got, marked)
	}
}

func TestWriteLearningsFileSucceedsWithUnreadableRoot(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, "learnings.md")
	if err := os.Mkdir(root, 0o755); err != nil {
		t.Fatalf("mkdir root learnings path: %v", err)
	}
	if _, err := CheckLearningsOwned(dir); err == nil {
		t.Fatal("CheckLearningsOwned() succeeded, want a refusal on an unreadable root file")
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	if err := WriteLearningsFile(dir, views); err != nil {
		t.Fatalf("WriteLearningsFile() error = %v, want success with an unreadable root file", err)
	}
	if fi, err := os.Stat(root); err != nil || !fi.IsDir() {
		t.Errorf("root path %s was disturbed (stat err=%v)", root, err)
	}
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	got, err := os.ReadFile(dot)
	if err != nil {
		t.Fatalf("read .flywheel/learnings.md: %v", err)
	}
	if !strings.Contains(string(got), "Terse") {
		t.Errorf(".flywheel/learnings.md lost the learning:\n%s", got)
	}
}

func TestWriteLearningsFileRefusesChangedDotFile(t *testing.T) {
	dir := t.TempDir()
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	if err := os.MkdirAll(filepath.Dir(dot), 0o755); err != nil {
		t.Fatalf("mkdir .flywheel: %v", err)
	}
	marked := []byte("# Learnings\n" + learningsMarker + "\nstale\n")
	if err := os.WriteFile(dot, marked, 0o644); err != nil {
		t.Fatalf("write marked dot file: %v", err)
	}
	other := filepath.Join(dir, "other.md")
	if err := os.WriteFile(other, []byte("another writer's file\n"), 0o644); err != nil {
		t.Fatalf("write other file: %v", err)
	}
	ofi, err := os.Stat(other)
	if err != nil {
		t.Fatalf("stat other file: %v", err)
	}
	lstat := func(path string) (os.FileInfo, error) { return ofi, nil }
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	err = writeLearningsFile(dir, views, lstat)
	if err == nil {
		t.Fatal("WriteLearningsFile() succeeded, want a refusal when the .flywheel file changed")
	} else if !strings.Contains(err.Error(), "another writer") {
		t.Errorf("refusal %q does not say the file changed hands", err)
	}
	got, rerr := os.ReadFile(dot)
	if rerr != nil {
		t.Fatalf("read dot file: %v", rerr)
	}
	if string(got) != string(marked) {
		t.Errorf("dot file changed to %q, want %q byte-for-byte", got, marked)
	}
}

func TestWriteLearningsFileCheckedAtRename(t *testing.T) {
	dir := t.TempDir()
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	if err := os.MkdirAll(filepath.Dir(dot), 0o755); err != nil {
		t.Fatalf("mkdir .flywheel: %v", err)
	}
	marked := []byte("# Learnings\n" + learningsMarker + "\nstale\n")
	if err := os.WriteFile(dot, marked, 0o644); err != nil {
		t.Fatalf("write marked dot file: %v", err)
	}
	replacement := filepath.Join(dir, "replacement.md")
	replaced := []byte("another writer's file\n")
	if err := os.WriteFile(replacement, replaced, 0o644); err != nil {
		t.Fatalf("write replacement: %v", err)
	}
	// The injected seam expresses the interleaving: the dot file is replaced
	// after the temp file is written but before the rename, exactly when the
	// pre-rename ownership re-check runs.
	var seamRan bool
	lstat := func(path string) (os.FileInfo, error) {
		if path == dot && !seamRan {
			seamRan = true
			if err := os.Rename(replacement, dot); err != nil {
				return nil, fmt.Errorf("replace dot file: %w", err)
			}
		}
		return os.Lstat(path)
	}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	err := writeLearningsFile(dir, views, lstat)
	if err == nil {
		t.Fatal("writeLearningsFile() succeeded, want a refusal when the dot file is replaced before the rename")
	} else if !strings.Contains(err.Error(), "another writer") {
		t.Errorf("refusal %q does not say the file changed hands", err)
	}
	if !seamRan {
		t.Error("the injected seam never ran; the write did not re-check ownership before the rename")
	}
	got, rerr := os.ReadFile(dot)
	if rerr != nil {
		t.Fatalf("read dot file: %v", rerr)
	}
	if string(got) != string(replaced) {
		t.Errorf("dot file was clobbered to %q, want the replacement %q left alone", got, replaced)
	}
	entries, err := os.ReadDir(filepath.Join(dir, ".flywheel"))
	if err != nil {
		t.Fatalf("read .flywheel: %v", err)
	}
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), "learnings-") {
			t.Errorf("temp file %s left behind after the refused write", e.Name())
		}
	}
}

func TestSanitise(t *testing.T) {
	cases := []struct{ in, want string }{
		{`run D:\secret-co\proj\scripts\validate.sh now`, "run <path> now"},
		{`see C:\Users\me\file.txt`, "see <path>"},
		{`copy D:/tools/build.exe`, "copy <path>"},
		{`log /home/me/proj/x.json`, "log <path>"},
		{`token ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA leaked`, "token <redacted> leaked"},
		{`key gho_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa here`, "key <redacted> here"},
		{`fetch ghs_012345678901234567890123`, "fetch <redacted>"},
		{`sk-abcdefghijklmnopqrstuvwxyz`, "<redacted>"},
		{`Authorization: Bearer abcdefghijklmnopqrstuvwxyz`, "Authorization: <redacted>"},
		{`password = "hunter2"`, "<redacted>"},
		{`token: abc123def456`, "<redacted>"},
		{`secret=super-secret-value`, "<redacted>"},
		{`key = 'quoted value'`, "<redacted>"},
		{`evidence .flywheel/runs/t1.r1.jsonl`, "evidence .flywheel/runs/t1.r1.jsonl"},
		{`path internal/foo/bar.go`, "path internal/foo/bar.go"},
		{`see https://github.com/suzworx/flywheel/issues/40`, "see https://github.com/suzworx/flywheel/issues/40"},
	}
	for _, c := range cases {
		if got := Sanitise(c.in); got != c.want {
			t.Errorf("Sanitise(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestFeedbackReportExportsUndismissedSanitised(t *testing.T) {
	dir := t.TempDir()
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning", Severity: "P1",
		Title:    "Gate rots unobserved",
		Observed: "the harness at D:\\secret-co\\proj\\scripts\\validate.sh failed for days; token ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA was in the log",
		Evidence: ".flywheel/runs/t1.r1.jsonl", Ask: "record the commit a gate last passed at"}); err != nil {
		t.Fatalf("AppendEvent() error = %v", err)
	}
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:01Z", Task: "t1", Kind: "learning", Severity: "P2",
		Title: "Dismissed leak", Observed: `C:\Users\owner\secret\x`, Evidence: "e2", Ask: "a2"}); err != nil {
		t.Fatalf("AppendEvent() error = %v", err)
	}
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:02Z", Task: "t1", Kind: "dismissed", ID: "L-02", Note: "done"}); err != nil {
		t.Fatalf("AppendEvent() error = %v", err)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	report := FeedbackReport("dev", Learnings(events))
	if !strings.Contains(report, "## L-01 — Gate rots unobserved") {
		t.Errorf("report does not include the undismissed learning:\n%s", report)
	}
	if strings.Contains(report, "Dismissed leak") {
		t.Errorf("report includes a dismissed learning:\n%s", report)
	}
	for _, leak := range []string{"secret-co", "ghp_AAAA", "C:\\Users\\owner"} {
		if strings.Contains(report, leak) {
			t.Errorf("report leaked %q:\n%s", leak, report)
		}
	}
	if !strings.Contains(report, "<path>") || !strings.Contains(report, "<redacted>") {
		t.Errorf("report lacks the redaction markers:\n%s", report)
	}
	if !strings.Contains(report, "observed: the harness at <path> failed for days; token <redacted> was in the log") {
		t.Errorf("report did not sanitise observed in place:\n%s", report)
	}
	if !strings.Contains(report, ".flywheel/runs/t1.r1.jsonl") {
		t.Errorf("report mangled the repo-relative evidence path:\n%s", report)
	}
}

func TestWriteFeedbackReportMatchesPrint(t *testing.T) {
	dir := t.TempDir()
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	report := FeedbackReport("dev", views)
	path := filepath.Join(dir, "out", "report.md")
	if err := WriteFeedbackReport(path, report); err != nil {
		t.Fatalf("WriteFeedbackReport() error = %v", err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(b) != report {
		t.Errorf("file content = %q, want the printed report %q", b, report)
	}
}

func TestFeedbackSubmitNeverIsRuleRefusal(t *testing.T) {
	cfg := Config{Version: 1, Workers: []Worker{{Name: "d", Adapter: "sim", Model: "m"}},
		Feedback: Feedback{Upstream: "owner/repo", Submit: "never"}}
	_, err := FeedbackSubmit(t.TempDir(), cfg, "dev", nil, FeedbackSubmitOptions{Yes: true})
	if !IsRuleRefusal(err) {
		t.Fatalf("FeedbackSubmit() error = %v, want a RuleRefusal", err)
	}
	if !strings.Contains(err.Error(), "never") {
		t.Errorf("RuleRefusal %q does not name the feedback.submit setting", err)
	}
}

func TestFeedbackSubmitNoUpstreamIsUsage(t *testing.T) {
	cfg := Config{Version: 1, Workers: []Worker{{Name: "d", Adapter: "sim", Model: "m"}},
		Feedback: Feedback{Submit: "ask"}}
	_, err := FeedbackSubmit(t.TempDir(), cfg, "dev", nil, FeedbackSubmitOptions{Yes: true})
	if !errors.Is(err, ErrFeedbackNoUpstream) {
		t.Fatalf("FeedbackSubmit() error = %v, want ErrFeedbackNoUpstream", err)
	}
}

func TestFeedbackSubmitWithoutYesSendsNothing(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{Version: 1, Workers: []Worker{{Name: "d", Adapter: "sim", Model: "m"}},
		Feedback: Feedback{Upstream: "owner/repo", Submit: "ask"}}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	called := false
	res, err := FeedbackSubmit(dir, cfg, "dev", views, FeedbackSubmitOptions{
		Yes: false, Gh: func(...string) error { called = true; return nil },
	})
	if err != nil {
		t.Fatalf("FeedbackSubmit() error = %v", err)
	}
	if !res.NotSent {
		t.Errorf("FeedbackSubmit() = %+v, want consent withheld", res)
	}
	if res.Sent || res.Outbox != "" {
		t.Errorf("FeedbackSubmit() = %+v, want nothing sent and no outbox", res)
	}
	if called {
		t.Error("gh was called without consent")
	}
	if !strings.Contains(res.Report, "L-01") {
		t.Errorf("Report %q does not show the learning it would send", res.Report)
	}
	if _, err := os.Stat(filepath.Join(dir, ".flywheel", "feedback", "outbox")); !os.IsNotExist(err) {
		t.Error("outbox was created without consent")
	}
}

func TestFeedbackSubmitParksReportWhenSendFails(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{Version: 1, Workers: []Worker{{Name: "d", Adapter: "sim", Model: "m"}},
		Feedback: Feedback{Upstream: "owner/repo", Submit: "ask"}}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	now := time.Date(2026, 9, 16, 10, 30, 0, 0, time.UTC)
	res, err := FeedbackSubmit(dir, cfg, "dev", views, FeedbackSubmitOptions{
		Yes: true,
		Gh:  func(...string) error { return errors.New("gh missing") },
		Now: func() time.Time { return now },
	})
	if err != nil {
		t.Fatalf("FeedbackSubmit() error = %v", err)
	}
	if res.Sent {
		t.Errorf("FeedbackSubmit() = %+v, want the send to have failed without an issue", res)
	}
	if res.Outbox == "" {
		t.Fatal("FeedbackSubmit() did not park the report in the outbox")
	}
	if want := filepath.Join(dir, ".flywheel", "feedback", "outbox", "20260916-103000-L-01.md"); res.Outbox != want {
		t.Errorf("Outbox = %q, want %q", res.Outbox, want)
	}
	b, err := os.ReadFile(res.Outbox)
	if err != nil {
		t.Fatalf("read outbox: %v", err)
	}
	if string(b) != res.Report {
		t.Errorf("outbox content = %q, want the exact report", b)
	}
}

func TestFeedbackSubmitSendsViaGH(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{Version: 1, Workers: []Worker{{Name: "d", Adapter: "sim", Model: "m"}},
		Feedback: Feedback{Upstream: "owner/repo", Submit: "ask"}}
	views := []LearningView{{ID: "L-01", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}}
	var got []string
	res, err := FeedbackSubmit(dir, cfg, "dev", views, FeedbackSubmitOptions{
		Yes: true, Gh: func(args ...string) error { got = append(got, args...); return nil },
	})
	if err != nil {
		t.Fatalf("FeedbackSubmit() error = %v", err)
	}
	if !res.Sent || res.Outbox != "" {
		t.Errorf("FeedbackSubmit() = %+v, want sent with no outbox", res)
	}
	joined := strings.Join(got, " ")
	for _, want := range []string{"issue", "create", "--repo", "owner/repo", "--title", "--body-file"} {
		if !strings.Contains(joined, want) {
			t.Errorf("gh args %q do not contain %q", got, want)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".flywheel", "feedback", "outbox")); !os.IsNotExist(err) {
		t.Error("outbox was created on a successful send")
	}
}

// TestFeedbackAddConcurrentSerialisesMutations is the concurrency guard for
// issue #260: two concurrent add mutations must not interleave. Each reports
// its own learning id and title — the id the append actually wrote — and the
// final artifact contains both learnings. Run it with -count=20; -race is
// unavailable on this host (no C compiler, so go test -race refuses).
func TestFeedbackAddConcurrentSerialisesMutations(t *testing.T) {
	dir := t.TempDir()
	type result struct {
		id, title  string
		aerr, rerr error
	}
	results := make([]result, 2)
	var wg sync.WaitGroup
	for i, title := range []string{"Alpha", "Beta"} {
		wg.Add(1)
		go func(i int, title string) {
			defer wg.Done()
			id, out, aerr, rerr := AddLearning(dir, "t1", "P1", title, "slow", "e1", "repeat", nil)
			results[i] = result{id: id, title: out, aerr: aerr, rerr: rerr}
		}(i, title)
	}
	wg.Wait()
	for i, r := range results {
		if r.aerr != nil {
			t.Errorf("AddLearning() %d append error = %v, want the learning recorded", i, r.aerr)
		}
		if r.rerr != nil {
			t.Errorf("AddLearning() %d render error = %v", i, r.rerr)
		}
		if r.id == "" || r.title == "" {
			t.Errorf("AddLearning() %d = (%q, %q), want a reported id and title", i, r.id, r.title)
		}
	}
	if results[0].id == results[1].id {
		t.Errorf("both concurrent adds reported the same id %q, want distinct L-01 and L-02", results[0].id)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	byID := map[string]string{}
	for _, l := range Learnings(events) {
		byID[l.ID] = l.Title
	}
	if len(byID) != 2 {
		t.Fatalf("learnings = %v, want exactly 2", byID)
	}
	for i, r := range results {
		if byID[r.id] != r.title {
			t.Errorf("AddLearning() %d reported id %q with title %q, but the log has %q for that id", i, r.id, r.title, byID[r.id])
		}
	}
	b, err := os.ReadFile(filepath.Join(dir, ".flywheel", "learnings.md"))
	if err != nil {
		t.Fatalf("read learnings.md: %v", err)
	}
	for _, title := range []string{"Alpha", "Beta"} {
		if !strings.Contains(string(b), title) {
			t.Errorf("learnings.md lacks %q:\n%s", title, b)
		}
	}
}

// TestRegenLearningsRebuildsDeletedArtifact checks regen rebuilds a deleted
// .flywheel/learnings.md from the event log and appends no event: the event
// count is unchanged (issue #254).
func TestRegenLearningsRebuildsDeletedArtifact(t *testing.T) {
	dir := t.TempDir()
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}); err != nil {
		t.Fatalf("AppendEvent() error = %v", err)
	}
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	if _, err := os.Stat(dot); !os.IsNotExist(err) {
		t.Fatal("learnings.md exists before regen, want it absent")
	}
	if err := RegenLearnings(dir); err != nil {
		t.Fatalf("RegenLearnings() error = %v", err)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	if len(events) != 1 || events[0].Kind != "learning" {
		t.Errorf("events = %+v, want the single learning unchanged (regen appends nothing)", events)
	}
	got, err := os.ReadFile(dot)
	if err != nil {
		t.Fatalf("read learnings.md: %v", err)
	}
	if !strings.Contains(string(got), "Terse") {
		t.Errorf("learnings.md lacks the learning:\n%s", got)
	}
}

// TestRegenLearningsUpToDateChangesNothing checks regen on an artifact that
// already matches the log exits 0 (no error) and leaves the file
// byte-identical, appending nothing.
func TestRegenLearningsUpToDateChangesNothing(t *testing.T) {
	dir := t.TempDir()
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}); err != nil {
		t.Fatalf("AppendEvent() error = %v", err)
	}
	events, err := ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	if err := WriteLearningsFile(dir, Learnings(events)); err != nil {
		t.Fatalf("WriteLearningsFile() error = %v", err)
	}
	before, err := os.ReadFile(filepath.Join(dir, ".flywheel", "learnings.md"))
	if err != nil {
		t.Fatalf("read learnings.md: %v", err)
	}
	if err := RegenLearnings(dir); err != nil {
		t.Fatalf("RegenLearnings() error = %v, want exit 0 on an up-to-date artifact", err)
	}
	after, err := os.ReadFile(filepath.Join(dir, ".flywheel", "learnings.md"))
	if err != nil {
		t.Fatalf("read learnings.md: %v", err)
	}
	if string(after) != string(before) {
		t.Errorf("learnings.md changed:\nbefore:\n%s\nafter:\n%s", before, after)
	}
	events, err = ReadEvents(dir)
	if err != nil {
		t.Fatalf("ReadEvents() error = %v", err)
	}
	if len(events) != 1 {
		t.Errorf("events = %d, want 1 (regen appends nothing)", len(events))
	}
}

// TestRegenLearningsRefusesHandMaintainedFile checks regen refuses a
// hand-maintained (unmarked) .flywheel/learnings.md exactly as the other
// paths do, leaving it byte-for-byte untouched.
func TestRegenLearningsRefusesHandMaintainedFile(t *testing.T) {
	dir := t.TempDir()
	dot := filepath.Join(dir, ".flywheel", "learnings.md")
	curated := []byte("# Learnings\n\n## Hand written, precious\ndo not lose me\n")
	if err := os.MkdirAll(filepath.Dir(dot), 0o755); err != nil {
		t.Fatalf("mkdir .flywheel: %v", err)
	}
	if err := os.WriteFile(dot, curated, 0o644); err != nil {
		t.Fatalf("write curated file: %v", err)
	}
	if err := AppendEvent(dir, Event{TS: "2026-09-16T00:00:00Z", Task: "t1", Kind: "learning", Severity: "P1", Title: "Terse", Observed: "slow", Evidence: "e1", Ask: "a1"}); err != nil {
		t.Fatalf("AppendEvent() error = %v", err)
	}
	err := RegenLearnings(dir)
	if err == nil {
		t.Fatal("RegenLearnings() succeeded, want a refusal on a hand-maintained file")
	}
	if !strings.Contains(err.Error(), ".flywheel") {
		t.Errorf("refusal %q does not name the .flywheel path", err)
	}
	got, rerr := os.ReadFile(dot)
	if rerr != nil {
		t.Fatalf("read curated file: %v", rerr)
	}
	if string(got) != string(curated) {
		t.Errorf("curated file changed to %q, want %q byte-for-byte", got, curated)
	}
}
