package flywheel

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// reviewThreadMarker proves flywheel generated a review thread file: it is
// matched on before any overwrite, so a hand-written file is never clobbered.
const reviewThreadMarker = "<!-- generated by flywheel from the event log; do not edit -->"

// threadRound is one completed (or, for the last, in-progress) review round.
type threadRound struct {
	n        int
	reviewed *Event // nil while the round is still in progress
	findings []Event
}

// reviewRounds groups the task's review_finding events by the agent review
// round that closed them; findings raised after the last agent round form a
// trailing round with no reviewed event.
func reviewRounds(events []Event, task string) []threadRound {
	var rounds []threadRound
	cur := threadRound{n: 1}
	for _, e := range events {
		if e.Task != task {
			continue
		}
		switch {
		case e.Kind == "review_finding":
			cur.findings = append(cur.findings, e)
		case agentReviewed(e):
			ev := e
			cur.reviewed = &ev
			rounds = append(rounds, cur)
			cur = threadRound{n: cur.n + 1}
		}
	}
	if len(cur.findings) > 0 {
		rounds = append(rounds, cur)
	}
	return rounds
}

// sha7 is the first seven characters of a tree or commit hash.
func sha7(s string) string {
	if len(s) > 7 {
		return s[:7]
	}
	return s
}

// orDash is s, or "-" when s is empty.
func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}

// RenderReviewThread renders the task's review thread as markdown (issue
// #389): one section per review round with its findings, each finding's
// current status (open, closed in round m, re-reported in round m, or
// dismissed) and the worker's answers under it, then the open blocking
// findings. It is derived from the event log only; every free-text field is
// sanitised.
func RenderReviewThread(events []Event, task string) []byte {
	workers := workerSessions(events, task)
	open := map[string]bool{}
	var blocking []string
	for _, f := range OpenFindings(events, task) {
		open[f.Finding] = true
		if blockingFinding(f) {
			blocking = append(blocking, f.Finding)
		}
	}
	dismissal := map[string]Event{}
	answers := map[string][]Event{}
	for _, e := range events {
		if e.Task != task || e.Kind != "finding_response" {
			continue
		}
		if leadDismissal(e, workers) {
			dismissal[e.Finding] = e
		} else {
			answers[e.Finding] = append(answers[e.Finding], e)
		}
	}
	rounds := reviewRounds(events, task)
	// A dismissal by id also closes any finding with the same file and claim.
	dismissedKey := map[string]Event{}
	for _, r := range rounds {
		for _, f := range r.findings {
			if d, ok := dismissal[f.Finding]; ok {
				dismissedKey[findingKey(f)] = d
			}
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Review thread: %s\n%s\n", task, reviewThreadMarker)
	for i, r := range rounds {
		if r.reviewed != nil {
			e := r.reviewed
			fmt.Fprintf(&b, "\n## Round %d — %s, %s, %s, tree %s\n", r.n, orDash(e.Verdict), orDash(e.Session), orDash(e.Model), orDash(sha7(e.Tree)))
			if e.Note != "" {
				fmt.Fprintf(&b, "\n%s\n", Sanitise(e.Note))
			}
		} else {
			fmt.Fprintf(&b, "\n## Round %d — in progress\n", r.n)
		}
		if len(r.findings) == 0 {
			b.WriteString("\nno findings\n")
			continue
		}
		b.WriteString("\n")
		for _, f := range r.findings {
			fmt.Fprintf(&b, "- **%s** [%s/%s] %s:%d — %s\n", f.Finding, f.Severity, orDash(f.Category), f.Path, f.LineNo, Sanitise(f.Title))
			fmt.Fprintf(&b, "  scenario: %s\n", Sanitise(orDash(f.Observed)))
			fmt.Fprintf(&b, "  fix hint: %s\n", Sanitise(orDash(f.Ask)))
			fmt.Fprintf(&b, "  status: %s\n", findingStatus(f, rounds[i+1:], open, dismissal, dismissedKey))
			for _, a := range answers[f.Finding] {
				fmt.Fprintf(&b, "  - %s %s: %s — %s\n", orDash(a.Session), orDash(a.Attempt), a.Verdict, Sanitise(orDash(a.Note)))
			}
		}
	}
	b.WriteString("\n## Open blocking findings\n\n")
	if len(blocking) == 0 {
		b.WriteString("none\n")
	} else {
		b.WriteString(strings.Join(blocking, ", ") + "\n")
	}
	return []byte(b.String())
}

// findingStatus is f's current status given the rounds after its own.
func findingStatus(f Event, later []threadRound, open map[string]bool, dismissal, dismissedKey map[string]Event) string {
	d, ok := dismissal[f.Finding]
	if !ok {
		d, ok = dismissedKey[findingKey(f)]
	}
	if ok {
		return fmt.Sprintf("dismissed by %s: %s", d.Session, Sanitise(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(d.Note), "dismissed:"))))
	}
	if open[f.Finding] {
		return "open"
	}
	for _, r := range later {
		if r.reviewed == nil {
			break
		}
		for _, g := range r.findings {
			if findingKey(g) == findingKey(f) {
				return fmt.Sprintf("re-reported in round %d as %s", r.n, g.Finding)
			}
		}
		return fmt.Sprintf("closed in round %d", r.n)
	}
	return "open"
}

// ReviewThreadPath is the generated review thread of task, relative to dir.
func ReviewThreadPath(task string) string {
	return filepath.ToSlash(filepath.Join(".flywheel", "reviews", task+".md"))
}

// reviewThreadOwned refuses an existing thread file without the marker.
func reviewThreadOwned(path string) error {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !strings.Contains(string(data), reviewThreadMarker) {
		return fmt.Errorf("%s exists without the flywheel marker and looks hand-written; move it aside and re-run — flywheel will not overwrite it", path)
	}
	return nil
}

// WriteReviewThread regenerates .flywheel/reviews/<task>.md from the event
// log, atomically (temp file plus rename). A file there without the marker is
// never overwritten: the ownership is checked before the render and again
// immediately before the rename.
func WriteReviewThread(dir, task string) error {
	reviews := filepath.Join(dir, ".flywheel", "reviews")
	path := filepath.Join(reviews, task+".md")
	if err := reviewThreadOwned(path); err != nil {
		return err
	}
	events, err := ReadEvents(dir)
	if err != nil {
		return err
	}
	return atomicWriteChecked(reviews, task+".md", "thread-*.md", RenderReviewThread(events, task), func() error {
		return reviewThreadOwned(path)
	})
}

// refreshReviewThread rewrites the task's review thread; a failure is only a
// progress warning, never an error of the caller.
func refreshReviewThread(dir, task string, w io.Writer) {
	if err := WriteReviewThread(dir, task); err != nil {
		progress(w, fmt.Sprintf("warning: review thread of %s not written: %v", task, err))
	}
}
