package flywheel

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// reviewThreadMarker proves flywheel generated a review thread file: it is
// matched on before any overwrite, so a hand-written file is never clobbered.
const reviewThreadMarker = "<!-- generated by flywheel from the event log; do not edit -->"

// threadRound is one completed (or, for the last, in-progress) review round.
type threadRound struct {
	n        int
	reviewed *Event // nil while the round is still in progress; a panel round's first member
	panel    []Event
	findings []Event
}

// reviewRounds groups the task's review_finding events by the agent review
// round that closed them; findings raised after the last agent round form a
// trailing round with no reviewed event. A panel round (issue #420) is one
// round: its members' reviewed events, in order, until a dimension repeats
// or a general review intervenes (as nextReviewRound counts), and its
// findings grouped by dimension in member order.
func reviewRounds(events []Event, task string) []threadRound {
	var rounds []threadRound
	cur := threadRound{n: 1}
	for _, e := range events {
		if e.Task != task {
			continue
		}
		switch {
		case e.Kind == "review_finding":
			cur.findings = append(cur.findings, e)
		case agentReviewed(e):
			ev := e
			dim := reviewDimension(e)
			if last := len(rounds) - 1; dim != "" && last >= 0 && len(rounds[last].panel) > 0 && !panelHas(rounds[last].panel, dim) {
				rounds[last].panel = append(rounds[last].panel, ev)
				rounds[last].findings = append(rounds[last].findings, cur.findings...)
				cur.findings = nil
				continue
			}
			cur.reviewed = &ev
			if dim != "" {
				cur.panel = []Event{ev}
			}
			rounds = append(rounds, cur)
			cur = threadRound{n: cur.n + 1}
		}
	}
	for i := range rounds {
		if r := &rounds[i]; len(r.panel) > 0 {
			order := map[string]int{}
			for j, p := range r.panel {
				order[reviewDimension(p)] = j
			}
			sort.SliceStable(r.findings, func(a, b int) bool { return order[r.findings[a].Category] < order[r.findings[b].Category] })
		}
	}
	if len(cur.findings) > 0 {
		rounds = append(rounds, cur)
	}
	return rounds
}

// panelHas reports whether a panel round already holds dimension dim.
func panelHas(panel []Event, dim string) bool {
	for _, e := range panel {
		if reviewDimension(e) == dim {
			return true
		}
	}
	return false
}

// sha7 is the first seven characters of a tree or commit hash.
func sha7(s string) string {
	if len(s) > 7 {
		return s[:7]
	}
	return s
}

// orDash is s, or "-" when s is empty.
func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}

// RenderReviewThread renders the task's review thread as markdown (issue
// #389): one section per review round with its findings, each finding's
// current status (open, closed in round m, re-reported in round m, or
// dismissed) and the worker's answers under it, then the open blocking
// findings. It is derived from the event log only; every free-text field is
// sanitised.
func RenderReviewThread(events []Event, task string) []byte {
	workers := workerSessions(events, task)
	open := map[string]bool{}
	var blocking []string
	for _, f := range OpenFindings(events, task) {
		open[f.Finding] = true
		if blockingFinding(f) {
			blocking = append(blocking, f.Finding)
		}
	}
	dismissal := map[string]Event{}
	answers := map[string][]Event{}
	for _, e := range events {
		if e.Task != task || e.Kind != "finding_response" {
			continue
		}
		if leadDismissal(e, workers) {
			dismissal[e.Finding] = e
		} else {
			answers[e.Finding] = append(answers[e.Finding], e)
		}
	}
	rounds := reviewRounds(events, task)
	// A dismissal by id also closes any finding with the same file and claim.
	dismissedKey := map[string]Event{}
	for _, r := range rounds {
		for _, f := range r.findings {
			if d, ok := dismissal[f.Finding]; ok {
				dismissedKey[findingKey(f)] = d
			}
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Review thread: %s\n%s\n", task, reviewThreadMarker)
	for i, r := range rounds {
		if len(r.panel) > 0 {
			fmt.Fprintf(&b, "\n## Round %d — review panel, tree %s\n\n", r.n, orDash(sha7(r.reviewed.Tree)))
			for _, p := range r.panel {
				fmt.Fprintf(&b, "- %s: %s, %s, %s, tree %s — %s\n", reviewDimension(p), orDash(p.Verdict), orDash(p.Session), orDash(p.Model), orDash(sha7(p.Tree)), Sanitise(orDash(p.Note)))
			}
		} else if r.reviewed != nil {
			e := r.reviewed
			fmt.Fprintf(&b, "\n## Round %d — %s, %s, %s, tree %s\n", r.n, orDash(e.Verdict), orDash(e.Session), orDash(e.Model), orDash(sha7(e.Tree)))
			if e.Note != "" {
				fmt.Fprintf(&b, "\n%s\n", Sanitise(e.Note))
			}
		} else {
			fmt.Fprintf(&b, "\n## Round %d — in progress\n", r.n)
		}
		if len(r.findings) == 0 {
			b.WriteString("\nno findings\n")
			continue
		}
		b.WriteString("\n")
		for j, f := range r.findings {
			if len(r.panel) > 0 && (j == 0 || r.findings[j-1].Category != f.Category) {
				if j > 0 {
					b.WriteString("\n")
				}
				fmt.Fprintf(&b, "### %s\n\n", orDash(f.Category))
			}
			fmt.Fprintf(&b, "- **%s** [%s/%s] %s:%d — %s\n", f.Finding, f.Severity, orDash(f.Category), f.Path, f.LineNo, Sanitise(f.Title))
			fmt.Fprintf(&b, "  scenario: %s\n", Sanitise(orDash(f.Observed)))
			fmt.Fprintf(&b, "  fix hint: %s\n", Sanitise(orDash(f.Ask)))
			fmt.Fprintf(&b, "  status: %s\n", findingStatus(f, rounds[i+1:], open, dismissal, dismissedKey))
			for _, a := range answers[f.Finding] {
				fmt.Fprintf(&b, "  - %s %s: %s — %s\n", orDash(a.Session), orDash(a.Attempt), a.Verdict, Sanitise(orDash(a.Note)))
			}
		}
	}
	// The matrix of the latest panel round, on the tree its last member
	// reviewed: pass, correct or missing per dimension it covered.
	for i := len(rounds) - 1; i >= 0; i-- {
		if p := rounds[i].panel; len(p) > 0 {
			var dims []string
			for _, e := range p {
				dims = append(dims, reviewDimension(e))
			}
			tree := p[len(p)-1].Tree
			fmt.Fprintf(&b, "\n## Panel verdict matrix — tree %s\n\n", orDash(sha7(tree)))
			m := VerdictMatrix(events, task, tree, dims)
			for _, d := range dims {
				fmt.Fprintf(&b, "- %s: %s\n", d, m[d])
			}
			break
		}
	}
	b.WriteString("\n## Open blocking findings\n\n")
	if len(blocking) == 0 {
		b.WriteString("none\n")
	} else {
		b.WriteString(strings.Join(blocking, ", ") + "\n")
	}
	return []byte(b.String())
}

// findingStatus is f's current status given the rounds after its own.
func findingStatus(f Event, later []threadRound, open map[string]bool, dismissal, dismissedKey map[string]Event) string {
	d, ok := dismissal[f.Finding]
	if !ok {
		d, ok = dismissedKey[findingKey(f)]
	}
	if ok {
		return fmt.Sprintf("dismissed by %s: %s", d.Session, Sanitise(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(d.Note), "dismissed:"))))
	}
	if open[f.Finding] {
		return "open"
	}
	for _, r := range later {
		if r.reviewed == nil {
			break
		}
		if len(r.panel) > 0 && !panelHas(r.panel, f.Category) {
			continue // a panel round that did not review this dimension
		}
		for _, g := range r.findings {
			if findingKey(g) == findingKey(f) {
				return fmt.Sprintf("re-reported in round %d as %s", r.n, g.Finding)
			}
		}
		return fmt.Sprintf("closed in round %d", r.n)
	}
	return "open"
}

// ReviewThreadPath is the generated review thread of task, relative to dir.
func ReviewThreadPath(task string) string {
	return filepath.ToSlash(filepath.Join(".flywheel", "reviews", task+".md"))
}

// reviewThreadOwned refuses an existing thread file without the marker.
func reviewThreadOwned(path string) error {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !strings.Contains(string(data), reviewThreadMarker) {
		return fmt.Errorf("%s exists without the flywheel marker and looks hand-written; move it aside and re-run — flywheel will not overwrite it", path)
	}
	return nil
}

// WriteReviewThread regenerates .flywheel/reviews/<task>.md from the event
// log, atomically (temp file plus rename). A file there without the marker is
// never overwritten: the ownership is checked before the render and again
// immediately before the rename.
func WriteReviewThread(dir, task string) error {
	reviews := filepath.Join(dir, ".flywheel", "reviews")
	path := filepath.Join(reviews, task+".md")
	if err := reviewThreadOwned(path); err != nil {
		return err
	}
	events, err := ReadEvents(dir)
	if err != nil {
		return err
	}
	return atomicWriteChecked(reviews, task+".md", "thread-*.md", RenderReviewThread(events, task), func() error {
		return reviewThreadOwned(path)
	})
}

// GroupThreadPath is the generated thread of a group's reviews (issue #420),
// relative to dir: .flywheel/reviews/group-<id>.md.
func GroupThreadPath(group string) string {
	return filepath.ToSlash(filepath.Join(".flywheel", "reviews", "group-"+GroupID(group)+".md"))
}

// RenderGroupThread renders a group's review thread as markdown (issue
// #420): one section per group review round — verdict, session, model, tree
// and its note (members, conflicts, gates) — with the findings it raised,
// each with the task it was routed to and its status (open, closed, or
// advisory for a minor or nit), then the open blocking integration findings.
func RenderGroupThread(events []Event, group string) []byte {
	gtask := GroupTask(group)
	open := map[string]bool{}
	seen := map[string]bool{}
	for _, e := range events {
		if e.Kind == "review_finding" && e.Reason == gtask && !seen[e.Task] {
			seen[e.Task] = true
			for _, f := range openIntegrationFindings(events, e.Task) {
				if f.Reason == gtask {
					open[f.Finding] = true
				}
			}
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Group review thread: %s\n%s\n", group, reviewThreadMarker)
	var pending, blocking []string
	round := 0
	for _, e := range events {
		switch {
		case e.Kind == "review_finding" && e.Reason == gtask:
			status := "closed"
			switch {
			case open[e.Finding]:
				status = "open"
				blocking = append(blocking, e.Finding+" ("+e.Task+")")
			case !blockingFinding(e):
				status = "advisory"
			}
			pending = append(pending, fmt.Sprintf("- **%s** [%s] on %s — %s:%d — %s\n  scenario: %s\n  fix hint: %s\n  status: %s\n",
				e.Finding, e.Severity, e.Task, e.Path, e.LineNo, Sanitise(e.Title), Sanitise(orDash(e.Observed)), Sanitise(orDash(e.Ask)), status))
		case e.Task == gtask && e.Kind == "group_reviewed":
			round++
			fmt.Fprintf(&b, "\n## Round %d — %s, %s, %s, tree %s\n\n%s\n\n", round, e.Verdict, orDash(e.Session), orDash(e.Model), orDash(sha7(e.Tree)), Sanitise(orDash(e.Note)))
			if len(pending) == 0 {
				b.WriteString("no findings\n")
			}
			b.WriteString(strings.Join(pending, ""))
			pending = nil
		}
	}
	b.WriteString("\n## Open blocking findings\n\n")
	if len(blocking) == 0 {
		b.WriteString("none\n")
	} else {
		b.WriteString(strings.Join(blocking, ", ") + "\n")
	}
	return []byte(b.String())
}

// WriteGroupThread regenerates the group's thread from the event log, as
// WriteReviewThread does a task's: atomically, never over a hand-written file.
func WriteGroupThread(dir, group string) error {
	reviews := filepath.Join(dir, ".flywheel", "reviews")
	name := "group-" + GroupID(group) + ".md"
	path := filepath.Join(reviews, name)
	if err := reviewThreadOwned(path); err != nil {
		return err
	}
	events, err := ReadEvents(dir)
	if err != nil {
		return err
	}
	return atomicWriteChecked(reviews, name, "thread-*.md", RenderGroupThread(events, group), func() error {
		return reviewThreadOwned(path)
	})
}

// refreshReviewThread rewrites the task's review thread; a failure is only a
// progress warning, never an error of the caller.
func refreshReviewThread(dir, task string, w io.Writer) {
	if err := WriteReviewThread(dir, task); err != nil {
		progress(w, fmt.Sprintf("warning: review thread of %s not written: %v", task, err))
	}
}
